//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiharNewsLive.ModelsWithDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_NewsSubCategoryMaster
    {
        public int SubCategoryID { get; set; }
        public int CategoryID { get; set; }
        public string SubNewsCategory { get; set; }
        public string SubNewsDesc { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        public virtual M_NewsCategoryMaster M_NewsCategoryMaster { get; set; }
    }
}
