//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiharNewsLive.ModelsWithDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_UserMaster
    {
        public string RegistrationID { get; set; }
        public int UserType { get; set; }
        public string UserName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Address { get; set; }
        public int LocationID { get; set; }
        public int PinCode { get; set; }
        public string EmailID { get; set; }
        public string ContactNo { get; set; }
        public string CurrentCompany { get; set; }
        public int PostAppliedFor { get; set; }
        public string Validity { get; set; }
        public Nullable<bool> IsApprovedByAdmin { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        public virtual M_LocationMasters M_LocationMasters { get; set; }
        public virtual M_MasterTables M_MasterTables { get; set; }
        public virtual M_MasterTables M_MasterTables1 { get; set; }
    }
}
